apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "istio-workshop.fullname" . }}-keycloak
spec:
  selector:    
    istio: ingressgateway
  servers:
  - hosts:
    - {{ .Values.ingress.hosts.keycloak }}
    port:
      name: http
      number: {{ .Values.ingress.port }}
      protocol: HTTP
